from pydantic import BaseModel, Field
from typing import Any, Optional

class LLMResponseMetadata(BaseModel):
    correlation_id: str = Field(description="Unique UUID for tracing this specific request")
    prompt_version: str = Field(default="v1", description="Version string for the prompt template")
    latency_ms: int = Field(description="Total round-trip time in milliseconds")
    prompt_tokens: Optional[int] = Field(default=None, description="Tokens used for the prompt context")
    completion_tokens: Optional[int] = Field(default=None, description="Tokens generated by the model")
    total_tokens: Optional[int] = Field(default=None, description="Total tokens consumed")

class LLMResponse(BaseModel):
    content: Any = Field(description="The generated output. Could be raw string or a parsed Pydantic object.")
    metadata: LLMResponseMetadata = Field(description="Telemetry and operational metadata for the request")

class LLMProviderError(Exception):
    """Base exception for LLM provider failures"""
    pass

class LLMTimeoutError(LLMProviderError):
    """Exception raised when the LLM provider times out"""
    pass

class LLMRateLimitError(LLMProviderError):
    """Exception raised when the LLM provider rate limits the request"""
    pass
