import pytest
import json
from unittest.mock import MagicMock
from agents.manual_test_agent import ManualTestAgent
from agents.schemas.qa_schemas import ScenariosListModel, TestScenario
from agents.schemas.execution_schemas import ManualTestCasesListModel, ManualTestCase
from agents.schemas.llm_schema import LLMResponse, LLMResponseMetadata

@pytest.fixture
def mock_gateway():
    return MagicMock()

def get_mock_llm_response(content: str) -> LLMResponse:
    metadata = LLMResponseMetadata(correlation_id="mock-1", latency_ms=10)
    return LLMResponse(content=content, metadata=metadata)

def test_manual_test_agent_vague_rejection(mock_gateway):
    agent = ManualTestAgent()
    agent.gateway = mock_gateway
    
    scenario = TestScenario(
        scenario_id="TS-01",
        requirement_id="REQ-01",
        risk_id="NONE",
        title="Test Login",
        description="Login",
        test_type="positive",
        priority="High",
        preconditions=[],
        test_data="None",
        expected_behavior="Success",
        automation_candidate=True,
        golden_candidate=False
    )
    
    scenarios = ScenariosListModel(scenarios=[scenario])
    
    mock_response = {
        "test_cases": [
            {
                "test_case_id": "TC-01",
                "story_id": "STORY-1",
                "requirement_id": "REQ-01",
                "acceptance_criteria_id": "AC-01",
                "risk_id": "NONE",
                "scenario_id": "TS-01",
                "title": "Test Login",
                "objective": "Verify login works",
                "preconditions": [],
                "test_data": "None",
                "steps": [{"step": "Enter credentials", "expected_result": "It works"}],
                "expected_result": "Verify it works perfectly",
                "priority": "High",
                "severity": "High",
                "test_type": "Functional",
                "automation_candidate": True,
                "golden_id": "NONE",
                "ai_specific_test": False
            }
        ]
    }
    
    mock_gateway.generate_text.return_value = get_mock_llm_response(json.dumps(mock_response))
    
    result = agent.generate_manual_test_cases(scenarios)
    
    assert result.is_success
    tc = result.data.test_cases[0]
    
    # Check that vague rejection hook intercepted it
    assert tc.expected_result == "NEEDS_CLARIFICATION: Vague expected result generated by AI"

def test_manual_test_agent_duplicate_rejection(mock_gateway):
    agent = ManualTestAgent()
    agent.gateway = mock_gateway
    
    scenario = TestScenario(
        scenario_id="TS-01",
        requirement_id="REQ-01",
        risk_id="NONE",
        title="Test Login",
        description="Login",
        test_type="positive",
        priority="High",
        preconditions=[],
        test_data="None",
        expected_behavior="Success",
        automation_candidate=True,
        golden_candidate=False
    )
    scenarios = ScenariosListModel(scenarios=[scenario])
    
    base_tc = {
        "test_case_id": "TC-01",
        "story_id": "STORY-1",
        "requirement_id": "REQ-01",
        "acceptance_criteria_id": "AC-01",
        "risk_id": "NONE",
        "scenario_id": "TS-01",
        "title": "Test Login",
        "objective": "Verify login",
        "preconditions": [],
        "test_data": "None",
        "steps": [],
        "expected_result": "User is successfully logged in",
        "priority": "High",
        "severity": "High",
        "test_type": "Functional",
        "automation_candidate": True,
        "golden_id": "NONE",
        "ai_specific_test": False
    }
    
    mock_response = {
        "test_cases": [
            base_tc,
            base_tc  # Duplicate!
        ]
    }
    
    mock_gateway.generate_text.return_value = get_mock_llm_response(json.dumps(mock_response))
    
    result = agent.generate_manual_test_cases(scenarios)
    
    assert result.is_success
    # Should only have 1 due to deduplication hook
    assert len(result.data.test_cases) == 1
