import os
import csv
import json
import logging
from typing import List, Dict, Any

try:
    import pandas as pd
    PANDAS_AVAILABLE = True
except ImportError:
    PANDAS_AVAILABLE = False

from agents.base_agent import BaseAgent
from agents.schemas.base_agent_schema import AgentInput, AgentOutput
from agents.schemas.qa_schemas import TestScenario, ScenariosListModel
from agents.schemas.execution_schemas import ManualTestCase, ManualTestCasesListModel

logger = logging.getLogger("ManualTestAgent")

class ManualTestAgent(BaseAgent[ManualTestCasesListModel]):
    """
    AI Agent that transforms Test Scenarios into detailed Manual Test Cases and exports CSV / Excel reports.
    """

    def __init__(self, provider_name: str = None):
        super().__init__("ManualTestAgent", provider_name)

    def generate_manual_test_cases(self, scenarios: ScenariosListModel) -> AgentOutput[ManualTestCasesListModel]:
        logger.info("Generating manual test cases for %d scenarios...", len(scenarios.scenarios))
        
        system_prompt = (
            "You are a Senior QA Automation & Manual Tester. "
            "Convert the provided test scenarios into detailed manual test cases.\n"
            "Rules:\n"
            "1. Steps must be executable by a human tester.\n"
            "2. Expected results must be highly specific.\n"
            "3. NO vague statements like 'verify it works' or 'verify it is correct'. Be explicit.\n"
            "4. Preserve traceability (IDs, requirements, risks).\n"
            "5. Do not invent requirements.\n"
            "6. Ensure no duplicate tests are generated.\n"
            "7. If a test verifies AI behavior, mark ai_specific_test=True.\n"
            "Output must conform exactly to the provided JSON schema."
        )

        prompt = f"Please generate manual test cases for these scenarios:\n\n{scenarios.model_dump_json(indent=2)}"

        input_data = AgentInput(
            prompt=prompt,
            system_instruction=system_prompt
        )
        
        result = self.execute(input_data, ManualTestCasesListModel)
        
        # Post-Processing Duplicate Detection
        if result.is_success and result.data and result.data.test_cases:
            unique_cases = []
            seen_titles = set()
            for tc in result.data.test_cases:
                title_lower = tc.title.lower().strip()
                if title_lower in seen_titles:
                    logger.warning("Duplicate test case detected and removed: %s", tc.title)
                    continue
                
                # Quality Gate: Reject vague expected results by replacing them with a NEED_CLARIFICATION string
                vague_terms = ["works", "is correct", "functions as expected", "looks good"]
                if any(vague in tc.expected_result.lower() for vague in vague_terms):
                    tc.expected_result = "NEEDS_CLARIFICATION: Vague expected result generated by AI"
                
                seen_titles.add(title_lower)
                unique_cases.append(tc)
                
            result.data.test_cases = unique_cases
            
        return result

    def export_reports(self, test_cases_model: ManualTestCasesListModel, output_dir: str = "reports"):
        os.makedirs(output_dir, exist_ok=True)
        if not test_cases_model or not test_cases_model.test_cases:
            return

        # Serialize
        data_list = [tc.model_dump() for tc in test_cases_model.test_cases]
        
        # 1. Export JSON
        json_path = os.path.join(output_dir, "manual-test-cases.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(data_list, f, indent=2)
            
        # Flatten steps for CSV/Excel
        flat_data = []
        for tc in test_cases_model.test_cases:
            tc_dict = tc.model_dump()
            # Convert steps list to formatted string
            steps_str = "\n".join([f"Step: {s.get('step', '')} -> Expected: {s.get('expected_result', '')}" for s in tc.steps])
            tc_dict['steps'] = steps_str
            tc_dict['preconditions'] = "\n".join(tc.preconditions)
            flat_data.append(tc_dict)

        # 2. Export CSV
        if flat_data:
            csv_path = os.path.join(output_dir, "manual-test-cases.csv")
            keys = flat_data[0].keys()
            with open(csv_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=keys)
                writer.writeheader()
                writer.writerows(flat_data)

        # 3. Export Excel
        if PANDAS_AVAILABLE and flat_data:
            excel_path = os.path.join(output_dir, "manual-test-cases.xlsx")
            df = pd.DataFrame(flat_data)
            try:
                df.to_excel(excel_path, index=False)
                logger.info("Successfully exported Excel report to '%s'", excel_path)
            except Exception as e:
                logger.error("Failed to generate Excel report: %s", e)
                
        logger.info("Successfully exported manual test cases to %s", output_dir)
