import os
import logging
from typing import Optional
from google import genai
from google.genai import types
from google.genai.errors import APIError
from agent.providers.base_provider import AIProvider

logger = logging.getLogger("GeminiProvider")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")

class GeminiProvider(AIProvider):
    """
    Enterprise Gemini AI Provider leveraging the modern Google Gen AI Python SDK (google-genai).
    """

    def __init__(self, model_name: Optional[str] = None, api_key: Optional[str] = None):
        # Support both GOOGLE_API_KEY (primary) and GEMINI_API_KEY (fallback)
        self.api_key = api_key or os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
        self.model_name = model_name or os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

        if not self.api_key or self.api_key == "your_key_here":
            logger.warning(
                "GOOGLE_API_KEY not configured or using default placeholder. "
                "Gemini AI features will operate in fallback mode."
            )
            self.client = None
        else:
            # Mask API key in logs to ensure credentials are never leaked
            masked_key = f"{self.api_key[:4]}...{self.api_key[-4:]}" if len(self.api_key) > 8 else "***"
            logger.info("Initializing GeminiProvider with model '%s' and key [%s]", self.model_name, masked_key)
            try:
                self.client = genai.Client(api_key=self.api_key)
            except Exception as err:
                logger.error("Failed to initialize google.genai.Client: %s", str(err))
                self.client = None

    def generate_text(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """
        Generates text using Google Gen AI Python SDK with error handling and logging.
        """
        if not self.client:
            return (
                "Gemini Provider Notice: GOOGLE_API_KEY environment variable is not set. "
                "Please configure a valid GOOGLE_API_KEY in your environment or .env file."
            )

        try:
            logger.info("Dispatching request to Gemini model '%s'", self.model_name)
            
            config_kwargs = {"temperature": 0.2}
            if system_instruction:
                config_kwargs["system_instruction"] = system_instruction
                
            config = types.GenerateContentConfig(**config_kwargs)

            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
                config=config
            )

            if response and hasattr(response, 'text') and response.text:
                return response.text.strip()
            
            logger.warning("Gemini returned empty text response.")
            return "No content generated by Gemini."

        except APIError as api_err:
            logger.error("Gemini API Error (Code: %s): %s", getattr(api_err, 'code', 'N/A'), str(api_err))
            return f"Gemini API Error: {str(api_err)}"
        except Exception as err:
            logger.error("Unexpected error during Gemini execution: %s", str(err))
            return f"Gemini Execution Error: {str(err)}"

    def analyze_failure(self, error_message: str, stack_trace: str, page_dom: Optional[str] = None) -> str:
        """
        Generates structured root-cause failure analysis from E2E test errors and DOM state.
        """
        system_instruction = (
            "You are an expert QA Automation Architect and AI Failure Analyzer. "
            "Analyze test failures and provide a clear, actionable root cause analysis and code fix in clean Markdown."
        )

        prompt = f"""### E2E Test Failure Log Analysis

**Error Message:**
```text
{error_message}
```

**Stack Trace:**
```text
{stack_trace}
```
"""

        if page_dom:
            truncated_dom = page_dom[:10000]
            prompt += f"\n**Page DOM Snippet (at failure):**\n```html\n{truncated_dom}\n```\n"

        prompt += "\nPlease analyze why the test failed and provide step-by-step recommendations to fix the UI test script or underlying web app issue."

        return self.generate_text(prompt, system_instruction=system_instruction)

    def generate_test_code(self, source_code: str, requirements: Optional[str] = None) -> str:
        """
        Generates Playwright Python test scripts from React component code.
        """
        system_instruction = (
            "You are a Senior SDET and QA Automation Architect. "
            "Generate complete, executable Playwright Python test scripts using pytest and standard Page Object Model patterns."
        )

        prompt = f"""Write a robust Playwright Python test script for the following source component:

```javascript
{source_code}
```
"""
        if requirements:
            prompt += f"\nAdditional Requirements:\n{requirements}\n"

        prompt += "\nOutput ONLY valid Python code inside a ```python ``` block."

        return self.generate_text(prompt, system_instruction=system_instruction)
